-- The Mortals — Supabase schema
-- Run this once in your Supabase project's SQL Editor.
-- All tables are public-readable; writes require an authenticated user (see policies.sql).

-- ============================================================
-- 1. COLUMNS  (whale-done, inkmagination, forteenlines, astronomical)
-- ============================================================
create table if not exists public.columns (
  slug          text primary key,
  name          text not null,
  tagline       text not null,
  description   text not null,
  image_url     text not null default '',
  color         text not null default '#1e56b5',
  sort_order    int  not null default 0,
  created_at    timestamptz not null default now()
);

-- ============================================================
-- 2. ARTICLES
-- ============================================================
do $$ begin
  create type article_genre as enum (
    'nonfiction', 'fiction-prose', 'fiction-poetry', 'review', 'other'
  );
exception when duplicate_object then null;
end $$;

create table if not exists public.articles (
  id                  bigint generated by default as identity primary key,
  slug                text not null unique,
  title               text not null,
  author              text not null,
  author_affiliation  text,
  date_label          text not null,                    -- human-facing date string e.g. "Jan 25, 2025"
  genre               article_genre not null default 'other',
  excerpt             text not null,
  content             text not null,
  image_url           text,
  column_slug         text references public.columns(slug) on delete set null,
  tags                text[] default '{}',
  published           boolean not null default true,
  published_at        timestamptz not null default now(),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index if not exists articles_published_at_idx on public.articles (published, published_at desc);
create index if not exists articles_column_slug_idx  on public.articles (column_slug);
create index if not exists articles_genre_idx        on public.articles (genre);

-- ============================================================
-- 3. VOLUMES + ISSUES
-- ============================================================
create table if not exists public.volumes (
  slug          text primary key,
  title         text not null,
  season        text not null,
  year          text not null,
  theme         text not null default '',
  image_url     text not null default '',
  sort_order    int  not null default 0,
  created_at    timestamptz not null default now()
);

create table if not exists public.issues (
  slug          text primary key,
  volume_slug   text references public.volumes(slug) on delete cascade,
  title         text not null,
  season        text not null,
  year          text not null,
  quote         text not null default '',
  quote_author  text not null default '',
  content       text not null default '',
  sort_order    int  not null default 0,
  created_at    timestamptz not null default now()
);

create index if not exists issues_volume_idx on public.issues (volume_slug);

-- ============================================================
-- 4. HERO SLIDES (homepage rotation)
-- ============================================================
create table if not exists public.hero_slides (
  id            bigint generated by default as identity primary key,
  image_url     text not null,
  alt_text      text not null default '',
  sort_order    int  not null default 0,
  active        boolean not null default true,
  created_at    timestamptz not null default now()
);

create index if not exists hero_slides_active_order_idx on public.hero_slides (active, sort_order);

-- ============================================================
-- 5. TEAM (current editorial board)
-- ============================================================
create table if not exists public.team_members (
  id            bigint generated by default as identity primary key,
  name          text not null,
  role          text not null,
  class_year    text,                       -- e.g. "'26"
  school        text,                       -- e.g. "BIPH"
  portrait_url  text,
  bio           text,
  sort_order    int  not null default 0,
  active        boolean not null default true,
  created_at    timestamptz not null default now()
);

create index if not exists team_members_active_order_idx on public.team_members (active, sort_order);

-- ============================================================
-- 6. ALUMNI (past editorial board)
-- ============================================================
create table if not exists public.alumni (
  id            bigint generated by default as identity primary key,
  name          text not null,
  role          text not null,
  class_year    text,
  school        text,
  portrait_url  text,
  note          text,
  sort_order    int  not null default 0,
  created_at    timestamptz not null default now()
);

create index if not exists alumni_sort_idx on public.alumni (sort_order);

-- ============================================================
-- 7. UPDATED_AT trigger for articles
-- ============================================================
create or replace function public.touch_updated_at() returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists articles_touch on public.articles;
create trigger articles_touch
  before update on public.articles
  for each row execute function public.touch_updated_at();
