-- Migration 003 — acknowledgements
-- Faculty + staff thank-you list shown on the About page. Moves the
-- previously hard-coded list into the DB so editors can manage it from
-- the panel (Acknowledgements tab).

create table if not exists public.acknowledgements (
  id          bigint generated by default as identity primary key,
  name        text not null,
  role        text not null default '',
  note        text not null default '',
  sort_order  int  not null default 0,
  created_at  timestamptz not null default now()
);

-- RLS — public read, authenticated write (mirrors the other content tables)
alter table public.acknowledgements enable row level security;

drop policy if exists "public read acknowledgements" on public.acknowledgements;
create policy "public read acknowledgements" on public.acknowledgements
  for select using (true);

drop policy if exists "auth write acknowledgements" on public.acknowledgements;
create policy "auth write acknowledgements" on public.acknowledgements
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- Seed the current list (only when the table is empty).
insert into public.acknowledgements (name, role, note, sort_order)
select * from (values
  ('Mr. Dust',     'Advisor & Mentor',              'Improving our ideas with concrete actions and constructive feedback', 0),
  ('Mr. Huizinga', 'Proofreader',                   'Proofreading our drafts from start to end; mentor to all three student magazine editors', 1),
  ('Mr. Quirk',    'Head of BIPH & AP Literature',  'Leading us to the publishing stage with unwavering support', 2),
  ('Ms. Hannah',   'English Department',            'Championing the literary community at BASIS', 3),
  ('Ms. Victoria', 'Club Advisor',                  'Guiding The Mortals as our club advisor and steady source of support', 4),
  ('Mr. Ken',      'Head of Operations',            'Head of Operations at our school — the person who prints every issue for us', 5),
  ('Mr. Slonim',   'Head of English, BASIS Network','Head of English for the BASIS network, championing student writing across campuses', 6)
) as v(name, role, note, sort_order)
where not exists (select 1 from public.acknowledgements);
