-- Migration 005 — leaders
--
-- The magazine's leadership roster: who runs it now, and who ran it before.
-- Deliberately separate from team_members (the editorial board) and alumni
-- (past contributors) — a leader is a distinct thing from either, so mixing
-- them into those tables would have forced people like Albert Wang to appear
-- as both a current board member and a former chief.
--
-- `former` splits the two groups. Former leaders carry the college they went
-- on to; current leaders leave it null.

create table if not exists public.leaders (
  id          bigint generated by default as identity primary key,
  name        text not null,
  role        text not null,
  college     text,
  former      boolean not null default false,
  active      boolean not null default true,
  sort_order  int  not null default 0,
  created_at  timestamptz not null default now()
);

-- RLS — public read, authenticated write (mirrors the other content tables)
alter table public.leaders enable row level security;

drop policy if exists "public read leaders" on public.leaders;
create policy "public read leaders" on public.leaders
  for select using (active = true);

drop policy if exists "auth write leaders" on public.leaders;
create policy "auth write leaders" on public.leaders
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- Seed the roster (only when the table is empty, so re-running is safe).
-- sort_order is per-group; the site orders by (former, sort_order) so the
-- current leadership always lists first.
insert into public.leaders (name, role, college, former, sort_order)
select * from (values
  -- Current leadership
  ('David Cheng', 'Editor in Chief',        null,          false, 0),
  ('Alex Huang',  'Editor in Chief',        null,          false, 1),
  ('David Zhu',   'Lead Website Developer', null,          false, 2),
  ('Joey Yip',    'Lead Website Developer', null,          false, 3),
  ('Morning Lu',  'HR Manager',             null,          false, 4),
  ('Katie Lam',   'Design Head',            null,          false, 5),
  ('Sherry You',  'Design Head',            null,          false, 6),
  -- Former leadership
  ('Timmy Zhang', 'Editor in Chief',        'Stanford',    true,  0),
  ('Albert Wang', 'Editor in Chief',        'Stanford',    true,  1),
  ('Connie Xu',   'Design Head',            'Swarthmore',  true,  2),
  ('Susan He',    'Design Head',            'Cambridge',   true,  3),
  ('Cindy Tian',  'Publicity Head',         'Grinnell',    true,  4),
  ('Johnny Li',   'Lead Website Developer', 'WashU',       true,  5)
) as v(name, role, college, former, sort_order)
where not exists (select 1 from public.leaders);
